document.write('<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog"');
document.write('	aria-labelledby="exampleModalLabel" aria-hidden="true">');
document.write('	<div class="modal-dialog" role="document">');
document.write('		<div class="modal-content">');
document.write('			<div class="modal-header">');
document.write('				<h5 class="modal-title" id="exampleModalLabel">登出</h5>');
document.write('				<button class="close" type="button" data-dismiss="modal"');
document.write('					aria-label="Close">');
document.write('					<span aria-hidden="true">×</span>');
document.write('				</button>');
document.write('			</div>');
document.write('			<div class="modal-body">選擇登出繼續動作</div>');
document.write('			<div class="modal-footer">');
document.write('				<button class="btn btn-secondary" type="button" data-dismiss="modal">取消</button>');
document.write('				<a class="btn btn-primary" href="#">登出</a>');
document.write('			</div>');
document.write('		</div>');
document.write('	</div>');
document.write('</div>');
