document.write('<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">');
document.write('	<!-- Sidebar - Brand -->');
document.write('	<a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">');
document.write('		<div class="sidebar-brand-icon rotate-n-15">');
document.write('			<i class="fas fa-laugh-wink"></i>');
document.write('		</div>');
document.write('		<div class="sidebar-brand-text mx-3">');
document.write('			委域');
document.write('		</div>');
document.write('	</a>');
document.write('	');
document.write('	<!-- 幫助中心管理	 -->');
document.write('	<hr class="sidebar-divider">');
document.write('	<li class="nav-item">');
document.write('		<a class="nav-link" href="#">');
document.write('			<i class="fas fa-fw fa-table"></i> ');
document.write('			<span>FAQ</span>');
document.write('		</a>');
document.write('	</li>');
document.write('    ');
document.write('	<!-- 活動管理 -->');
document.write('	<hr class="sidebar-divider">');
document.write('	<div class="sidebar-heading">活動管理</div>');
document.write('		<li class="nav-item">');
document.write('		<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseActivity" aria-expanded="true" aria-controls="collapseActivity"> ');
document.write('			<i class="fas fa-fw fa-cog"></i> ');
document.write('			<span>活動</span>');
document.write('		</a>');
document.write('		<div id="collapseActivity" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">');
document.write('			<div class="bg-white py-2 collapse-inner rounded">');
document.write('				<a class="collapse-item" href="#">活動管理</a>');
document.write('			</div>');
document.write('		</div>');
document.write('	</li>');
document.write('	');
document.write('		');
document.write('	<!-- 二手買賣管理 -->');
document.write('	<hr class="sidebar-divider">');
document.write('	<div class="sidebar-heading">二手買賣管理</div>');
document.write('		<li class="nav-item">');
document.write('		<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProduct" aria-expanded="true" aria-controls="collapseProduct"> ');
document.write('			<i class="fas fa-fw fa-cog"></i> ');
document.write('			<span>二手買賣</span>');
document.write('		</a>');
document.write('		<div id="collapseProduct" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">');
document.write('			<div class="bg-white py-2 collapse-inner rounded">');
document.write('				<a class="collapse-item" href="#">檢舉管理</a>');
document.write('				<a class="collapse-item" href="#">商品管理</a>');
document.write('				<a class="collapse-item" href="#">訂單管理</a>');
document.write('			</div>');
document.write('		</div>');
document.write('	</li>');
document.write('');
document.write('	<!-- 搬家 -->');
document.write('	<hr class="sidebar-divider">');
document.write('	<div class="sidebar-heading">搬家管理</div>');
document.write('		<li class="nav-item">');
document.write('		<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMove" aria-expanded="true" aria-controls="collapseMove"> ');
document.write('			<i class="fas fa-fw fa-cog"></i> ');
document.write('			<span>搬家</span>');
document.write('		</a>');
document.write('		<div id="collapseMove" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">');
document.write('			<div class="bg-white py-2 collapse-inner rounded">');
document.write('				<a class="collapse-item" href="/CFA104G3/back_end/move/moveRequestManage.jsp">申請單管理</a>');
document.write('				<a class="collapse-item" href="#">訂單管理</a>');
document.write('			</div>');
document.write('		</div>');
document.write('	</li>');
document.write('	');
document.write('	<!-- 會員管理 -->');
document.write('	<hr class="sidebar-divider">');
document.write('	<div class="sidebar-heading">會員管理</div>');
document.write('	<li class="nav-item">');
document.write('		<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMember" aria-expanded="true" aria-controls="collapseMember"> ');
document.write('			<i class="fas fa-fw fa-cog"></i> ');
document.write('			<span>會員</span>');
document.write('		</a>');
document.write('		<div id="collapseMember" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">');
document.write('			<div class="bg-white py-2 collapse-inner rounded">');
document.write('				<a class="collapse-item" href="#">會員資料</a>');
document.write('			</div>');
document.write('		</div>');
document.write('	</li>');
document.write('	');
document.write('	<!-- 會員權限管理 -->');
document.write('	<hr class="sidebar-divider">');
document.write('	<div class="sidebar-heading">管理員權限</div>');
document.write('	<li class="nav-item">');
document.write('		<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseManager" aria-expanded="true" aria-controls="collapseManager"> ');
document.write('			<i class="fas fa-fw fa-cog"></i> ');
document.write('			<span>管理員</span>');
document.write('		</a>');
document.write('		<div id="collapseManager" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">');
document.write('			<div class="bg-white py-2 collapse-inner rounded">');
document.write('				<a class="collapse-item" href="#">權限管理</a>');
document.write('			</div>');
document.write('		</div>');
document.write('	</li>');
document.write('	');
document.write('	<!-- 摺疊 -->');
document.write('	<hr class="sidebar-divider d-none d-md-block">');
document.write('	<div class="text-center d-none d-md-inline">');
document.write('		<button class="rounded-circle border-0" id="sidebarToggle"></button>');
document.write('	</div>');
document.write('</ul>');