document.write('<nav');
document.write('	class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">');
document.write('');
document.write('	<!-- Sidebar Toggle (Topbar) -->');
document.write('	<button id="sidebarToggleTop"');
document.write('		class="btn btn-link d-md-none rounded-circle mr-3">');
document.write('		<i class="fa fa-bars"></i>');
document.write('	</button>');
document.write('');
document.write('	<!-- Topbar Search -->');
document.write('	<form');
document.write('		class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">');
document.write('		<div class="input-group">');
document.write('			<input type="text" class="form-control bg-light border-0 small"');
document.write('				placeholder="Search for..." aria-label="Search"');
document.write('				aria-describedby="basic-addon2">');
document.write('			<div class="input-group-append">');
document.write('				<button class="btn btn-primary" type="button">');
document.write('					<i class="fas fa-search fa-sm"></i>');
document.write('				</button>');
document.write('			</div>');
document.write('		</div>');
document.write('	</form>');
document.write('');
document.write('	<!-- Topbar Navbar -->');
document.write('	<ul class="navbar-nav ml-auto">');
document.write('');
document.write('		<!-- Nav Item - Search Dropdown (Visible Only XS) -->');
document.write('		<li class="nav-item dropdown no-arrow d-sm-none"><a');
document.write('			class="nav-link dropdown-toggle" href="#" id="searchDropdown"');
document.write('			role="button" data-toggle="dropdown" aria-haspopup="true"');
document.write('			aria-expanded="false"> <i class="fas fa-search fa-fw"></i>');
document.write('		</a> <!-- Dropdown - Messages -->');
document.write('			<div');
document.write('				class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"');
document.write('				aria-labelledby="searchDropdown">');
document.write('				<form class="form-inline mr-auto w-100 navbar-search">');
document.write('					<div class="input-group">');
document.write('						<input type="text" class="form-control bg-light border-0 small"');
document.write('							placeholder="Search for..." aria-label="Search"');
document.write('							aria-describedby="basic-addon2">');
document.write('						<div class="input-group-append">');
document.write('							<button class="btn btn-primary" type="button">');
document.write('								<i class="fas fa-search fa-sm"></i>');
document.write('							</button>');
document.write('						</div>');
document.write('					</div>');
document.write('				</form>');
document.write('			</div></li>');
document.write('');
document.write('		<!-- Nav Item - Alerts -->');
document.write('		<li class="nav-item dropdown no-arrow mx-1"><a');
document.write('			class="nav-link dropdown-toggle" href="#" id="alertsDropdown"');
document.write('			role="button" data-toggle="dropdown" aria-haspopup="true"');
document.write('			aria-expanded="false"> <i class="fas fa-bell fa-fw"></i> <!-- Counter - Alerts -->');
document.write('				<span class="badge badge-danger badge-counter">3+</span>');
document.write('		</a> <!-- Dropdown - Alerts -->');
document.write('			<div');
document.write('				class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"');
document.write('				aria-labelledby="alertsDropdown">');
document.write('				<h6 class="dropdown-header">Alerts Center</h6>');
document.write('				<a class="dropdown-item d-flex align-items-center" href="#">');
document.write('					<div class="mr-3">');
document.write('						<div class="icon-circle bg-primary">');
document.write('							<i class="fas fa-file-alt text-white"></i>');
document.write('						</div>');
document.write('					</div>');
document.write('					<div>');
document.write('						<div class="small text-gray-500">December 12, 2019</div>');
document.write('						<span class="font-weight-bold">A new monthly report is');
document.write('							ready to download!</span>');
document.write('					</div>');
document.write('				</a> <a class="dropdown-item d-flex align-items-center" href="#">');
document.write('					<div class="mr-3">');
document.write('						<div class="icon-circle bg-success">');
document.write('							<i class="fas fa-donate text-white"></i>');
document.write('						</div>');
document.write('					</div>');
document.write('					<div>');
document.write('						<div class="small text-gray-500">December 7, 2019</div>');
document.write('						$290.29 has been deposited into your account!');
document.write('					</div>');
document.write('				</a> <a class="dropdown-item d-flex align-items-center" href="#">');
document.write('					<div class="mr-3">');
document.write('						<div class="icon-circle bg-warning">');
document.write('							<i class="fas fa-exclamation-triangle text-white"></i>');
document.write('						</div>');
document.write('					</div>');
document.write('					<div>');
document.write('						<div class="small text-gray-500">December 2, 2019</div>');
document.write('						Spending Alert: We\'ve noticed unusually high spending for your');
document.write('						account.');
document.write('					</div>');
document.write('				</a> <a class="dropdown-item text-center small text-gray-500" href="#">Show');
document.write('					All Alerts</a>');
document.write('			</div></li>');
document.write('');
document.write('		<!-- Nav Item - Messages -->');
document.write('		<li class="nav-item dropdown no-arrow mx-1"><a');
document.write('			class="nav-link dropdown-toggle" href="#" id="messagesDropdown"');
document.write('			role="button" data-toggle="dropdown" aria-haspopup="true"');
document.write('			aria-expanded="false"> <i class="fas fa-envelope fa-fw"></i> <!-- Counter - Messages -->');
document.write('				<span class="badge badge-danger badge-counter">7</span>');
document.write('		</a> <!-- Dropdown - Messages -->');
document.write('			<div');
document.write('				class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"');
document.write('				aria-labelledby="messagesDropdown">');
document.write('				<h6 class="dropdown-header">Message Center</h6>');
document.write('				<a class="dropdown-item d-flex align-items-center" href="#">');
document.write('					<div class="dropdown-list-image mr-3">');
document.write('						<img class="rounded-circle"');
document.write('							src="/CFA104G3/asset/img/undraw_profile_1.svg"');
document.write('							alt="...">');
document.write('						<div class="status-indicator bg-success"></div>');
document.write('					</div>');
document.write('					<div class="font-weight-bold">');
document.write('						<div class="text-truncate">Hi there! I am wondering if you');
document.write('							can help me with a problem I\'ve been having.</div>');
document.write('						<div class="small text-gray-500">Emily Fowler · 58m</div>');
document.write('					</div>');
document.write('				</a> <a class="dropdown-item d-flex align-items-center" href="#">');
document.write('					<div class="dropdown-list-image mr-3">');
document.write('						<img class="rounded-circle"');
document.write('							src="/CFA104G3/asset/img/undraw_profile_2.svg"');
document.write('							alt="...">');
document.write('						<div class="status-indicator"></div>');
document.write('					</div>');
document.write('					<div>');
document.write('						<div class="text-truncate">I have the photos that you');
document.write('							ordered last month, how would you like them sent to you?</div>');
document.write('						<div class="small text-gray-500">Jae Chun · 1d</div>');
document.write('					</div>');
document.write('				</a> <a class="dropdown-item d-flex align-items-center" href="#">');
document.write('					<div class="dropdown-list-image mr-3">');
document.write('						<img class="rounded-circle"');
document.write('							src="/CFA104G3/asset/img/undraw_profile_3.svg"');
document.write('							alt="...">');
document.write('						<div class="status-indicator bg-warning"></div>');
document.write('					</div>');
document.write('					<div>');
document.write('						<div class="text-truncate">Last month\'s report looks great,');
document.write('							I am very happy with the progress so far, keep up the good work!</div>');
document.write('						<div class="small text-gray-500">Morgan Alvarez · 2d</div>');
document.write('					</div>');
document.write('				</a> <a class="dropdown-item d-flex align-items-center" href="#">');
document.write('					<div class="dropdown-list-image mr-3">');
document.write('						<img class="rounded-circle"');
document.write('							src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="...">');
document.write('						<div class="status-indicator bg-success"></div>');
document.write('					</div>');
document.write('					<div>');
document.write('						<div class="text-truncate">Am I a good boy? The reason I ask');
document.write('							is because someone told me that people say this to all dogs, even');
document.write('							if they aren\'t good...</div>');
document.write('						<div class="small text-gray-500">Chicken the Dog · 2w</div>');
document.write('					</div>');
document.write('				</a> <a class="dropdown-item text-center small text-gray-500" href="#">Read');
document.write('					More Messages</a>');
document.write('			</div></li>');
document.write('');
document.write('		<div class="topbar-divider d-none d-sm-block"></div>');
document.write('');
document.write('		<!-- Nav Item - User Information -->');
document.write('		<li class="nav-item dropdown no-arrow"><a');
document.write('			class="nav-link dropdown-toggle" href="#" id="userDropdown"');
document.write('			role="button" data-toggle="dropdown" aria-haspopup="true"');
document.write('			aria-expanded="false"> <span');
document.write('				class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas');
document.write('					McGee</span> <img class="img-profile rounded-circle"');
document.write('				src="/CFA104G3/asset/img/undraw_profile.svg">');
document.write('		</a> <!-- Dropdown - User Information -->');
document.write('			<div');
document.write('				class="dropdown-menu dropdown-menu-right shadow animated--grow-in"');
document.write('				aria-labelledby="userDropdown">');
document.write('				<a class="dropdown-item" href="#"> <i');
document.write('					class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Profile');
document.write('				</a> <a class="dropdown-item" href="#"> <i');
document.write('					class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i> Settings');
document.write('				</a> <a class="dropdown-item" href="#"> <i');
document.write('					class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i> Activity');
document.write('					Log');
document.write('				</a>');
document.write('				<div class="dropdown-divider"></div>');
document.write('				<a class="dropdown-item" href="#" data-toggle="modal"');
document.write('					data-target="#logoutModal"> <i');
document.write('					class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>');
document.write('					Logout');
document.write('				</a>');
document.write('			</div></li>');
document.write('	</ul>');
document.write('');
document.write('</nav>');
