document.write('    <footer class="border-top">');
document.write('        <div class="container px-4 px-lg-5">');
document.write('            <div class="row gx-4 gx-lg-5 justify-content-center">');
document.write('                <div class="col-md-10 col-lg-8 col-xl-7">');
document.write('<!-- 					<ul class="list-inline text-center"> -->');
document.write('<!-- 						<li class="list-inline-item"><a href="#!"> <span -->');
document.write('<!-- 								class="fa-stack fa-lg"> <i -->');
document.write('<!-- 									class="fas fa-circle fa-stack-2x"></i> <i -->');
document.write('<!-- 									class="fab fa-github fa-stack-1x fa-inverse"></i> -->');
document.write('<!-- 							</span> -->');
document.write('<!-- 						</a></li> -->');
document.write('<!-- 					</ul> -->');
document.write('					<div class="small text-center text-muted fst-italic">Copyright &copy; 委域</div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('    </footer>');
