document.write('  <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">');
document.write('        <div class="container px-4 px-lg-5">');
document.write('            <a class="navbar-brand" href="index.html">委域</a>');
document.write('            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"');
document.write('                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">');
document.write('                Menu');
document.write('                <i class="fas fa-bars"></i>');
document.write('            </button>');
document.write('            <div class="collapse navbar-collapse" id="navbarResponsive">');
document.write('                <ul class="navbar-nav md py-4 py-lg-0">');
document.write('                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">關於我們</a></li>');
document.write('                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="front_end/news/homePage.jsp">最新消息</a></li>');
document.write('                    <li class="nav-item dropdown">');
document.write('                    <a class="nav-link px-lg-3 py-3 py-lg-4 dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">服務</a>');
document.write('                   		<ul class="dropdown-menu dropdown-menu-end"');
document.write('							aria-labelledby="navbarDropdownBlog">');
document.write('							<li><a class="dropdown-item" href="front_end/move/homePage.jsp">前往搬家</a></li>');
document.write('							<li><a class="dropdown-item" href="front_end/product/homePage.jsp">前往二手商城</a></li>');
document.write('							<li><a class="dropdown-item" href="front_end/activity/homePage.jsp">前往活動</a></li>');
document.write('						</ul>');
document.write('                    </li>');
document.write('                  	<li class="nav-item dropdown">');
document.write('						<a class="nav-link px-lg-3 py-3 py-lg-4 dropdown-toggle" id="navbarDropdownHelp" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">幫助中心</a>');
document.write('						<ul class="dropdown-menu dropdown-menu-end"');
document.write('							aria-labelledby="navbarDropdownHelp">');
document.write('							<li><a class="dropdown-item" href="front_end/faq/homePage.jsp">FAQ</a></li>');
document.write('							<li><a class="dropdown-item" href="contact.html">聯絡我們</a></li>');
document.write('						</ul>');
document.write('					</li>');
document.write('                </ul>');
document.write('                <ul class="navbar-nav ms-auto py-4 py-lg-0">');
document.write('                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="front_end/member/register.jsp">註冊</a></li>');
document.write('                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="front_end/member/login.jsp">登入</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('        </div>');
document.write('    </nav>');
